name: Terraform Deploy

on:
  pull_request:
    branches:
      - devel
      - stage
      - prod
    types: [closed]
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    env:
      AWS_REGION: us-east-1
      BUCKET_NAME: devops-terraform-aws
      TF_WORKING_DIRECTORY: terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get latest successful run ID of 'Build Node App'
        id: get_run_id
        run: |
          WORKFLOW_NAME="Build Node App"
          REPO="${{ github.repository }}"
          TOKEN="${{ secrets.GITHUB_TOKEN }}"

          # Get workflow ID by name
          WORKFLOW_ID=$(curl -s -H "Authorization: Bearer $TOKEN" \
            https://api.github.com/repos/$REPO/actions/workflows \
            | jq -r ".workflows[] | select(.name==\"$WORKFLOW_NAME\") | .id")

          # Get latest successful run
          RUN_ID=$(curl -s -H "Authorization: Bearer $TOKEN" \
            "https://api.github.com/repos/$REPO/actions/workflows/$WORKFLOW_ID/runs?status=success&per_page=1" \
            | jq -r ".workflow_runs[0].id")

          echo "Latest run ID: $RUN_ID"
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Download artifact from previous workflow
        uses: actions/download-artifact@v4
        with:
          name: build
          run-id: ${{ steps.get_run_id.outputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: build/

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIRECTORY }}
        run: terraform init

      - name: Terraform Workspace Creation and Selection
        working-directory: ${{ env.TF_WORKING_DIRECTORY }}
        run: |
          terraform workspace new ${{ vars.ENV }}
          terraform workspace select ${{ vars.ENV }}

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIRECTORY }}
        run: terraform validate -var 'bucket_name=${{ env.BUCKET_NAME }}'

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIRECTORY }}
        run: terraform plan -var 'bucket_name=${{ env.BUCKET_NAME }}'
