name: Terraform Deploy

on:
  pull_request:
    branches:
      - devel
      - stage
      - prod
    types: [closed]
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '15'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install package
        run: npm install @mgarciam200593/rdicidr

      - name: LS
        run: ls -la

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2