name: Deploy NPM App

on:
  pull_request:
    branches:
      - devel
      - stage
      - prod
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Linter
        run: npm run lint

      - name: Formatter
        run: npm run prettier

      - name: Run Tests
        env:
          CI: true
        run: npm run test

      - name: Build
        run: npm run build