name: Deploy NPM App

on:
  pull_request:
    branches:
      - devel
      - stage
      - prod
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh jq -y

      - name: Get build run-id via GitHub CLI
        id: get_run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          RUN_ID=$(gh api \
            repos/${{ github.repository }}/actions/workflows/build-app.yml/runs \
            -F head_sha=${{ github.event.pull_request.head.sha }} \
            --jq '.workflow_runs[0].id')
          echo "::set-output name=id::$RUN_ID"

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          run-id: ${{ steps.get_run.outputs.id }}
          path: ./build

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
